### ISSUE TITLE
Only DNS

### ISSUE THREAD

**Issue by Rimander** [lxdcn/NEPacketTunnelVPNDemo#4]
Can i use this code only for DNS?
I need use other DNS only.

**Comment by davlxd** [comment]
Not quite understand your requirements.
  - Alter Wifi or 4G DNS programmingly without involve NetworkExtension?  I've never tried, but the DNS API I used belongs to [NetworkExtension](https://developer.apple.com/documentation/networkextension/nednssettings#//apple_ref/occ/cl/NEDNSSettings), chances are odd.
  - Set a dummy tunnel without using it, then override systematic DNS setting?  This maybe feasible, you [exclude all the traffic](https://github.com/lxdcn/NEPacketTunnelVPNDemo/blob/master/NEPacketTunnelVPNDemoTunnel/PacketTunnelProvider.swift#L51), [match all domains](https://github.com/lxdcn/NEPacketTunnelVPNDemo/blob/master/NEPacketTunnelVPNDemoTunnel/PacketTunnelProvider.swift#L60) and hoping it will override system DNS, instead of only effective against tunnel traffic. Still, I've never tried.

**Comment by Rimander** [comment]
Okey, Thanks
